version: '3.9'
services:
  web:
    depends_on:
      - db
    build:
      # context: src
      context: .
      dockerfile: ./Dockerfile
    # env_file: ./database.env
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      # Expose [HOST:CONTAINER]
      - 3030:3030
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: sdc
      # POSTGRES_USER: dockeru
      # POSTGRES_PASSWORD: dockerp
    ports:
      # - "27017"
      - 5438:5432
    volumes:
      - my-db:/var/lib/postgresql/data
      - ./sql/1createtbs.sql:/docker-entrypoint-initdb.d/1createtbs.sql
      # - ./sql/schematest.sql:/docker-entrypoint-initdb.d/schematest.sql
volumes:
  my-db: